Repository mondaycom/vibe-storybook-components, pull requests merged in 2023-10, with the labels that each got.

#19 fix(UsageGuidelines): wrap content in a span
  src/components/usage-guidelines/usage-guidelines.jsx
Labels: PR: Bugfix 🐛

#20 Add mising color tokens
  src/styles/tokens/colors.scss
Labels: PR: New Feature 🕹, PR: unreviewed

#22 Replace Rubik with Noto Sans Hebrew
  .storybook/preview-head.html
  src/styles/tokens/typography.scss
Labels: PR: New Feature 🕹, PR: unreviewed

#24 Origin/docs/sergeyro/storybook usage guidelines story
  .storybook/preview.tsx
  src/components/link/link.jsx
  src/components/usage-guidelines/__stories__/usage-guidelines.mdx
  src/components/usage-guidelines/__stories__/usage-guidelines.stories.tsx
Labels: PR: Documentation 📖

#23 docs(Storybook): document UsageGuidelines
  .storybook/main.ts
  .storybook/preview.tsx
  src/components/link/link.jsx
  src/components/usage-guidelines/README.md
  src/components/usage-guidelines/__stories__/usage-guidelines.mdx
  src/components/usage-guidelines/__stories__/usage-guidelines.stories.tsx
  src/components/usage-guidelines/usage-guidelines.jsx
  src/components/usage-guidelines/usage-guidelines.scss
Labels: PR: Documentation 📖

#27 infra: test-workflow.yml - remove push trigger
  .github/workflows/test-workflow.yml
Labels: PR: Internal 🏠

#26 docs: contibuting.md + components_documentation_guidelines.md
  COMPONENTS_DOCUMENTATION_GUIDELINES.md
  CONTRIBUTING.md
Labels: PR: Documentation 📖

#28 createStoryMetaSettings.js add ignoreControlsPropNamesArray
  src/functions/createStoryMetaSettings.js
Labels: PR: New Feature 🕹

#30 feat: createMetastorySettings - string type for ContentElement controls, disable action controls
  src/functions/createStoryMetaSettings.js
Labels: PR: New Feature 🕹

#29 Implement attention box, tip, alpha warning, deprecated warning components in vibe storybook components 4856297572
  src/components/alpha-warning/__stories__/alpha-warning.mdx
  src/components/alpha-warning/__stories__/alpha-warning.stories.tsx
  src/components/alpha-warning/alpha-warning.tsx
  src/components/deprecated-warning/__stories__/deprecated-warning.mdx
  src/components/deprecated-warning/__stories__/deprecated-warning.stories.tsx
  src/components/deprecated-warning/deprecated-warning.tsx
  src/components/tip/README.md
  src/components/tip/__stories__/tip.mdx
  src/components/tip/__stories__/tip.stories.tsx
  src/components/tip/tip.jsx
  src/components/tip/tip.module.scss
  src/components/tip/tip.scss
  src/components/tip/tip.tsx
  src/styles/tokens/colors.scss
Labels: PR: New Feature 🕹

#33 feat: add StatusTag
  src/components/status-tag/__stories__/status-tag.mdx
  src/components/status-tag/__stories__/status-tag.stories.tsx
  src/components/status-tag/status-tag.module.scss
  src/components/status-tag/status-tag.tsx
  src/styles/tokens/colors.scss
Labels: PR: New Feature 🕹

#35 Export components withStaticProps
  src/components/alpha-warning/alpha-warning.tsx
  src/components/deprecated-warning/deprecated-warning.tsx
  src/components/status-tag/__stories__/status-tag.stories.tsx
  src/components/tip/__stories__/tip.stories.tsx
  src/components/tip/tip.tsx
  src/helpers/components/Flex/Flex.tsx
  src/helpers/components/Link/Link.tsx
  src/types/withStaticProps.ts
Labels: PR: Internal 🏠

#46 docs: CSS_MODULES_MIGRATION.md
  CSS_MODULES_MIGRATION.md
Labels: PR: Documentation 📖

#36 docs: TYPESCRIPT_MIGRATION.md
  TYPESCRIPT_MIGRATION.md
  src/components/tip/tip.tsx
  src/helpers/components/Flex/Flex.tsx
  src/helpers/types/index.ts
  src/types/ElementContent.ts
  src/types/index.ts
Labels: PR: Documentation 📖

#34 Export Tip, AlphaWarning, DeprecatedWarning components
  src/components/alpha-warning/alpha-warning.tsx
  src/components/anchor-list-item/anchor-list-item.jsx
  src/components/color-description/color-description.jsx
  src/components/component-description/component-description.jsx
  src/components/component-name/component-name.jsx
  src/components/component-rule/component-rule.jsx
  src/components/component-rules/component-rules.jsx
  src/components/deprecated-warning/deprecated-warning.tsx
  src/components/doc-footer/doc-footer.jsx
  src/components/frame/frame.jsx
  src/components/function-arguments/function-argument.jsx
  src/components/function-arguments/function-arguments.jsx
  src/components/index.ts
  src/components/information-box-title/information-box-title.jsx
  src/components/information-box/information-box.jsx
  src/components/link-component/link-component.jsx
  src/components/link/link.jsx
  src/components/multiple-story-elements-wrapper/multiple-story-elements-wrapper.jsx
  src/components/paragraph/paragraph.jsx
  src/components/related-component/related-component.jsx
  src/components/related-components/related-components.jsx
  src/components/section-name/section-name.jsx
  src/components/status-tag/status-tag.tsx
  src/components/story-description/story-description.jsx
  src/components/tip/tip.tsx
  src/components/tip/tipConstants.ts
  src/components/title/title.jsx
  src/components/token-table/token-table-head-item.jsx
  src/components/token-table/token-table-row.jsx
  src/components/token-table/token-table.jsx
  src/components/unstyled-list-item/unstyled-list-item.jsx
  src/components/unstyled-list/unstyled-list.jsx
  src/components/usage-guidelines/usage-guidelines.jsx
  src/components/visual-description/visual-description.jsx
  src/helpers/components/Flex/Flex.tsx
  src/helpers/components/Icons/Check.tsx
  src/helpers/components/Icons/CloseSmall.tsx
  src/helpers/components/Link/Link.tsx
  src/helpers/types/VibeComponent.ts
  src/helpers/types/VibeComponentProps.ts
  src/types/index.ts
  storybook/components/component-name/component-name-decorator.jsx
Labels: PR: Bugfix 🐛

#47 feat: mixin sb-basic-text - disable font smoothing
  src/styles/mixins/_typography.scss
Labels: PR: New Feature 🕹

#48 Add sidebar item
  src/components/index.ts
  src/components/sidebar-item/__stories__/sidebar-item.mdx
  src/components/sidebar-item/__stories__/sidebar-item.stories.tsx
  src/components/sidebar-item/sidebar-item.tsx
  storybook/components/component-name/component-name-decorator.jsx
  storybook/components/index.js
Labels: PR: New Feature 🕹

#51 CSS modules migration: < UnstyledList />, < UnstyledListItem />, < Title />
  src/components/title/title.jsx
  src/components/title/title.module.scss
  src/components/unstyled-list-item/unstyled-list-item.jsx
  src/components/unstyled-list-item/unstyled-list-item.module.scss
  src/components/unstyled-list/unstyled-list.jsx
Labels: PR: Internal 🏠

#53 chore: prettier cleanup
  src/components/title/title.jsx
  src/components/unstyled-list-item/unstyled-list-item.jsx
Labels: PR: Internal 🏠

#55 Migrated < InformationBox />, < InformationBoxTitle />, < Frame /> to CSS modules
  src/components/frame/frame.jsx
  src/components/frame/frame.module.scss
  src/components/information-box-title/information-box-title.jsx
  src/components/information-box-title/information-box-title.module.scss
  src/components/information-box-title/information-box-title.scss
  src/components/information-box/information-box.jsx
  src/components/information-box/information-box.module.scss
Labels: PR: Internal 🏠

#57 Migrated < DocFooter />, < Frame />, < Paragraph /> and also child component <SectionName /> to TS
  src/components/doc-footer/doc-footer.tsx
  src/components/frame/frame.jsx
  src/components/frame/frame.tsx
  src/components/paragraph/paragraph.jsx
  src/components/paragraph/paragraph.tsx
  src/components/section-name/section-name.tsx
Labels: PR: Internal 🏠

#60 TS migration: < ComponentRule />, < ComponentRules />
  src/components/component-rule/component-rule-constants.ts
  src/components/component-rule/component-rule.tsx
  src/components/component-rules/component-rules.tsx
Labels: PR: Internal 🏠

#58 Migrated <AnchorListItem>, <ComponentDescription>, <ComponentName> components to TS
  src/components/anchor-list-item/anchor-list-item.jsx
  src/components/anchor-list-item/anchor-list-item.tsx
  src/components/component-description/component-description.jsx
  src/components/component-description/component-description.tsx
  src/components/component-name/component-name.tsx
Labels: PR: Internal 🏠

#67 TS migration: < UsageGuidelines />, < VisualDescription />
  src/components/usage-guidelines/usage-guidelines.tsx
  src/components/visual-description/visual-description.tsx
Labels: PR: Internal 🏠

#59 feat: migrated < Paragrapgh />, < MultipleStoryElementsWrapper />, < Link /> to scss modules
  src/components/link/link.jsx
  src/components/link/link.module.scss
  src/components/multiple-story-elements-wrapper/multiple-story-elements-wrapper.jsx
  src/components/multiple-story-elements-wrapper/multiple-story-elements-wrapper.module.scss
  src/components/paragraph/paragraph.jsx
  src/components/paragraph/paragraph.module.scss
Labels: PR: Internal 🏠

#72 infra: add build into test-workflow.yml
  .github/workflows/test-workflow.yml
Labels: PR: Internal 🏠

#70 TS migration: < SectionName />, < RelatedComponent />, < RelatedComponents />
  src/components/related-component/related-component.tsx
  src/components/related-components/related-components.tsx
  src/components/section-name/section-name.tsx
Labels: PR: Internal 🏠

#65 Convert UnstyledList UnstyledListItem Title to TSX
  package-lock.json
  package.json
  src/components/title/title.jsx
  src/components/title/title.tsx
  src/components/unstyled-list-item/unstyled-list-item.jsx
  src/components/unstyled-list-item/unstyled-list-item.tsx
  src/components/unstyled-list/unstyled-list.jsx
  src/components/unstyled-list/unstyled-list.tsx
Labels: PR: Internal 🏠

#74 Migrated < FunctionArgument />, < FunctionArguments />, < MultipleStoryElementsWrapper /> to TS
  src/components/function-arguments/function-argument.tsx
  src/components/function-arguments/function-arguments.jsx
  src/components/function-arguments/function-arguments.tsx
  src/components/multiple-story-elements-wrapper/multiple-story-elements-wrapper.tsx
Labels: PR: Internal 🏠

#73 feat: Migrate < ComponentRule />, < ComponentRules /> to css modules
  src/components/component-rule/component-rule.module.scss
  src/components/component-rule/component-rule.tsx
  src/components/component-rules/component-rules.module.scss
  src/components/component-rules/component-rules.tsx
Labels: PR: Internal 🏠

#84 docs: Add story for < ComponentName /> component
  src/components/component-name/__stories__/component-name.mdx
  src/components/component-name/__stories__/component-name.stories.tsx
Labels: PR: Documentation 📖

#81 Migrated < AnchorListItem />, < ComponentName />, < DocFooter /> to CSS modules
  src/components/anchor-list-item/anchor-list-item.module.scss
  src/components/anchor-list-item/anchor-list-item.tsx
  src/components/component-name/component-name.module.scss
  src/components/component-name/component-name.tsx
  src/components/doc-footer/doc-footer.module.scss
  src/components/doc-footer/doc-footer.tsx
Labels: PR: Internal 🏠

#79 Feat: add theme switching to storybook
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
Labels: PR: Documentation 📖

#85 chore: fix package-lock.json
  package-lock.json
Labels: PR: Internal 🏠

#86 chore: fix theme switcher type error
  .storybook/preview.tsx
Labels: PR: Bugfix 🐛

#87 fix: < ComponentName /> use text-color-fixed-dark
  src/components/component-name/component-name.module.scss
Labels: PR: Bugfix 🐛

#88 fix: dependency issue, upgrade storybook ^7.5.0
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#94 docs: Create basic story for < VisualDescription />, < ColorDescription />
  .storybook/main.ts
  public/visual-description.png
  src/components/color-description/__stories__/color-description.mdx
  src/components/color-description/__stories__/color-description.stories.tsx
  src/components/visual-description/__stories__/visual-description.mdx
  src/components/visual-description/__stories__/visual-description.stories.tsx
Labels: PR: Documentation 📖

#32 ci: add storybook and chromatic workflows
  .github/workflows/chromatic.yml
  .github/workflows/publish-storybook.yml
  src/components/usage-guidelines/usage-guidelines.module.scss
  src/components/usage-guidelines/usage-guidelines.tsx
Labels: PR: Internal 🏠

#96 Migrated the component to TS
  src/functions/createComponentTemplate.jsx
  src/functions/createComponentTemplate.tsx
  src/functions/createStoryMetaSettings.ts
Labels: PR: Internal 🏠

#97 Created story from Paragraph and Frame components
  src/components/frame/__stories__/frame.mdx
  src/components/frame/__stories__/frame.stories.tsx
  src/components/paragraph/__stories__/paragraph.mdx
  src/components/paragraph/__stories__/paragraph.stories.tsx
Labels: PR: Documentation 📖

#95 docs: add story for < TokenTable />
  src/components/token-table/__stories__/token-table.mdx
  src/components/token-table/__stories__/token-table.stories.tsx
Labels: PR: Documentation 📖

#93 docs: create basic story for < ComponentDescription />, < UnstyledList /> + < UnstyledListItem />
  src/components/component-description/__stories__/component-description.mdx
  src/components/component-description/__stories__/component-description.stories.tsx
  src/components/unstyled-list/__stories__/unstyled-list.mdx
  src/components/unstyled-list/__stories__/unstyled-list.stories.tsx
Labels: PR: Documentation 📖

#83 feat: Migrate < Link />, < StoryDescription /> to ts
  src/components/deprecated-warning/deprecated-warning.tsx
  src/components/link/LinkConstants.ts
  src/components/link/link.jsx
  src/components/link/link.tsx
  src/components/story-description/story-description.jsx
  src/components/story-description/story-description.tsx
Labels: PR: New Feature 🕹

#106 chore: prettier fix
  src/components/deprecated-warning/deprecated-warning.tsx
Labels: PR: Internal 🏠

#99 docs: replace logo in storybook
  .storybook/logo.png
Labels: PR: Documentation 📖

#100 fix(SidebarItem): add ellipsis to item name
  src/components/sidebar-item/sidebar-item.module.scss
  src/components/sidebar-item/sidebar-item.tsx
Labels: PR: Bugfix 🐛

#108 fix(SidebarItem): flex the container
  src/components/sidebar-item/sidebar-item.module.scss
  src/components/sidebar-item/sidebar-item.tsx
Labels: PR: Bugfix 🐛

#109 docs: add story for < ComponentRules />, < DocFooter />
  src/components/component-rules/__stories__/component-rules.mdx
  src/components/component-rules/__stories__/component-rules.stories.tsx
  src/components/doc-footer/__stories__/doc-footer.mdx
  src/components/doc-footer/__stories__/doc-footer.stories.tsx
Labels: PR: Documentation 📖

#110 prettier fix + component-name.stories change text
  src/components/component-name/__stories__/component-name.stories.tsx
  src/components/component-rules/__stories__/component-rules.stories.tsx
  src/components/doc-footer/__stories__/doc-footer.stories.tsx
Labels: PR: Internal 🏠

#111 docs: add story for < Link /> and < StoryDescription />
  src/components/link/__stories__/link.mdx
  src/components/link/__stories__/link.stories.tsx
  src/components/story-description/__stories__/story-description.mdx
  src/components/story-description/__stories__/story-description.stories.tsx
Labels: PR: Documentation 📖

#112 Created basic story for < SectionName />, < AnchorListItem />
  src/components/anchor-list-item/__stories__/anchor-list-item.mdx
  src/components/anchor-list-item/__stories__/anchor-list-item.stories.tsx
  src/components/section-name/__stories__/section-name.mdx
  src/components/section-name/__stories__/section-name.stories.tsx
Labels: PR: Documentation 📖

#113 Add Tip to preview.tsx
  .storybook/preview.tsx
Labels: PR: Internal 🏠

#114 Add story for < Title /> component
  src/components/title/__stories__/title.mdx
  src/components/title/__stories__/title.stories.tsx
Labels: PR: Documentation 📖

#115 docs: add story for < FunctionArguments /> and < InformationBox />
  src/components/function-arguments/__stories__/function-arguments.mdx
  src/components/function-arguments/__stories__/function-arguments.stories.tsx
  src/components/function-arguments/function-argument.tsx
  src/components/information-box/__stories__/information-box.mdx
  src/components/information-box/__stories__/information-box.stories.tsx
Labels: PR: Documentation 📖

#116 chore: cleanup
  src/components/component-rule/component-rule.tsx
  src/components/component-rules/component-rules.tsx
  src/components/information-box/information-box.tsx
Labels: PR: Bugfix 🐛
