Repository mondaycom/vibe-storybook-components, pull requests merged in 2023-11, with the labels that each got.

#119 fix: <InformationBoxTitle> use <Link>
  src/components/information-box-title/information-box-title.tsx
  src/components/related-component/related-component.tsx
Labels: PR: Bugfix 🐛

#121 docs: remove hacker theme from storybook
  .storybook/preview-head.html
  .storybook/preview.tsx
Labels: PR: Documentation 📖

#120 fix: <DocFooter> use <Link>
  src/components/doc-footer/doc-footer.tsx
Labels: PR: Bugfix 🐛

#122 fix: <InformationBoxTitle> Link withoutSpacing
  src/components/information-box-title/information-box-title.tsx
Labels: PR: Bugfix 🐛

#123 fix: reduce <InformationBox> line-height from 24px to 20px
  src/components/information-box/information-box.module.scss
  src/styles/tokens/typography.scss
Labels: PR: Bugfix 🐛

#124 feat: <Link> add target prop
  src/components/link/LinkConstants.ts
  src/components/link/link.tsx
Labels: PR: New Feature 🕹

#126 feat(DeprecatedWarning): add children
  src/components/deprecated-warning/deprecated-warning.tsx
Labels: PR: New Feature 🕹

#129 fix: <Frame> make className, noBorder, noGutter props not required
  src/components/frame/frame.tsx
Labels: PR: Bugfix 🐛
